LANGUAGES = {
    'ar': {
        'name': 'العربية',
        'flag': '🇸🇦',
        'start': '🎮 بدء اللعبة الجديدة',
        'select_bottles': 'اختر عدد الزجاجات:',
        'select_empty': 'كم عدد الزجاجات الفارغة؟',
        'bottle_num': 'الزجاجة',
        'select_color': 'اختر اللون:',
        'color_counter': 'تم إدخال هذا اللون',
        'times': 'مرة',
        'delete_last': '🗑️ حذف آخر لون',
        'clear_bottle': '🧹 مسح الزجاجة',
        'done': '✅ تم',
        'solving': '🔍 جاري البحث عن الحل...',
        'solution_found': '🎉 تم إيجاد حل!',
        'steps': 'خطوة',
        'next_game': '🔄 لعبة جديدة',
        'help': '🆘 المساعدة',
        'remaining': 'متبقي',
        'of': 'من',
        'empty_bottles': 'زجاجة فارغة',
        'color_selection': 'اختيار الألوان',
        'quick_colors': 'ألوان سريعة',
        'all_colors': 'عرض كل الألوان',
        'back': '🔙 رجوع',
        'confirm': 'تأكيد',
        'cancel': 'إلغاء',
        'error': '❌ خطأ',
        'success': '✅ تم بنجاح',
        'warning': '⚠️ تحذير',
        'welcome': '🎮 مرحباً بك في بوت حل لغز فرز الألوان!',
        'instructions': '📝 *كيفية اللعب:*\n1. اختر عدد الزجاجات\n2. اختر عدد الفارغة\n3. املأ الألوان\n4. احصل على الحل',
        'select_language': '🌍 اختر لغتك:'
    },
    'en': {
        'name': 'English',
        'flag': '🇺🇸',
        'start': '🎮 Start New Game',
        'select_bottles': 'Select number of bottles:',
        'select_empty': 'How many empty bottles?',
        'bottle_num': 'Bottle',
        'select_color': 'Select color:',
        'color_counter': 'This color entered',
        'times': 'times',
        'delete_last': '🗑️ Delete last',
        'clear_bottle': '🧹 Clear bottle',
        'done': '✅ Done',
        'solving': '🔍 Searching for solution...',
        'solution_found': '🎉 Solution found!',
        'steps': 'steps',
        'next_game': '🔄 New game',
        'help': '🆘 Help',
        'remaining': 'remaining',
        'of': 'of',
        'empty_bottles': 'empty bottles',
        'color_selection': 'Color Selection',
        'quick_colors': 'Quick Colors',
        'all_colors': 'All Colors',
        'back': '🔙 Back',
        'confirm': 'Confirm',
        'cancel': 'Cancel',
        'error': '❌ Error',
        'success': '✅ Success',
        'warning': '⚠️ Warning',
        'welcome': '🎮 Welcome to Water Sort Puzzle Solver!',
        'instructions': '📝 *How to play:*\n1. Select bottles count\n2. Select empty bottles\n3. Fill colors\n4. Get solution',
        'select_language': '🌍 Choose your language:'
    }
}
